name: Professional-CI

on: 
  push:
    branches: [ main ]

jobs:
  lint-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Linter
        run: echo "Checking code style... Done! No errors found"


  build-job:
    runs-on: ubuntu-latest
    needs: lint-jobs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          mkdir -p output
          echo "Building..." > output/app.log
          

  
  test-job:
    runs-on: ubuntu-latest
    needs: build-job 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Unit Tests
        run: |
          echo "Running tests..."
          # Просто имитация теста: проверяем версию системы
          node -v
          python3 --version


